<a href="https://colab.research.google.com/github/rlaxodns/google-/blob/main/keras07_mlp2_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#x의 데이터가 range로 지정되는 경우


In [13]:
# 환경 준비
import numpy as np
from keras.models import Sequential
from keras.layers import Dense

In [26]:
# 데이터
x= np.array(range(10))
print(x)

x= np.array(range(3,10))
print(x)

x = np.array([range(10), range(21,31), range(201,211)])
print(x)

y = np.array([2,4,6,8,10,12,14,16,18,20])

print(x.shape)
x=x.T
print(y.shape)

[0 1 2 3 4 5 6 7 8 9]
[3 4 5 6 7 8 9]
[[  0   1   2   3   4   5   6   7   8   9]
 [ 21  22  23  24  25  26  27  28  29  30]
 [201 202 203 204 205 206 207 208 209 210]]
(3, 10)
(10,)


In [27]:
# model
model = Sequential()
model.add(Dense(1, input_dim=3))

In [28]:
# compile & fit
model.compile(loss='mse', optimizer='adam')
model.fit(x,y,epochs=100, batch_size=1)

Epoch 1/100
10/10 [==============================] - 0s 2ms/step - loss: 43525.1562
Epoch 2/100
10/10 [==============================] - 0s 2ms/step - loss: 42549.6953
Epoch 3/100
10/10 [==============================] - 0s 2ms/step - loss: 41587.4414
Epoch 4/100
10/10 [==============================] - 0s 2ms/step - loss: 40641.6328
Epoch 5/100
10/10 [==============================] - 0s 2ms/step - loss: 39709.5547
Epoch 6/100
10/10 [==============================] - 0s 2ms/step - loss: 38794.1953
Epoch 7/100
10/10 [==============================] - 0s 2ms/step - loss: 37894.6562
Epoch 8/100
10/10 [==============================] - 0s 2ms/step - loss: 37010.6797
Epoch 9/100
10/10 [==============================] - 0s 2ms/step - loss: 36142.1797
Epoch 10/100
10/10 [==============================] - 0s 2ms/step - loss: 35289.7578
Epoch 11/100
10/10 [==============================] - 0s 2ms/step - loss: 34451.9766
Epoch 12/100
10/10 [==============================] - 0s 2ms/step - loss: 

In [30]:
# predict
loss = model.evaluate(x,y)
result = model.predict([[10,31,211]])

print(loss)
print(result)

1/1 [==============================] - 0s 98ms/step
2008.054443359375
[[42.534855]]
